### ISSUE TITLE
Feature Engineering

### ISSUE THREAD

**Issue by liavcueto375** [busi732/BUSI732_F24_Team3#10]

**Comment by letian0102** [comment]
**Objective**
As a data scientist, I want to examine the data to understand what features I need to extract from the data in order to feed to the model. I will create the "feature_engineering.py" file that stores functions about creating and modifying new and existing features. The functions will then be applied and reused in jupyter notebooks as need.

**Acceptance Criteria**
1. At least three functions that creates new features in the form of dataframes.
2. The functions should have easy to read comments and clear variable names.
