### ISSUE TITLE
Define Optimization Problem (variables, constraints)

### ISSUE THREAD

**Issue by liavcueto375** [busi732/BUSI732_F24_Team3#11]

**Comment by cccmichic** [comment]
Primary Objectives

Operational Efficiency and Cost Minimization are crucial aspects of a wind turbine optimization model, as they directly impact the economic viability and financial performance of a wind farm.

By analyzing and optimizing the operational performance of the turbines,the company can reduce costs related to maintenance, equipment wear, downtime, and inefficiencies;

Maximize Energy Production: Utilize real-time wind data (e.g., available windspeed, power output, rotor speed) to ensure turbines operate at optimal power generation levels, improving revenue from energy sales.
Minimize Operational Costs: Reduce wear on components (e.g., bearings, blades, inverters) by optimizing rotor speed, blade angles, and temperature management, which minimizes maintenance costs and extends equipment lifespan.
Reduce Downtime: Schedule predictive and preventive maintenance during periods of low wind to prevent unplanned outages and maximize the turbine's operational hours and production minutes.
Enhance Efficiency: Optimize the balance between active and reactive power to reduce energy losses, meet grid stability requirements, and avoid penalties while ensuring peak efficiency.
Model Research

Power Output Optimization
Relevant Variables:
WEC: ava. Power
WEC: max. Power
WEC: min. Power
WEC: ava. available P from wind
WEC: ava. available P technical reasons
Rationale: Power output is the most direct measure of a turbine's efficiency. The objective here is to maximize the amount of energy the turbine generates while minimizing any losses. The available power from wind and the actual power output to calculate the efficiency ratio, which compares how much energy is available in the wind and how much the turbine actually captures.
Cost Implications:If the turbine isn’t operating at peak efficiency (e.g., due to suboptimal rotor speed, improper blade angle, or mechanical issues), there are risk of losing potential revenue. Operational efficiency can be improved by optimizing these factors, thereby reducing lost revenue and minimizing wear on the equipment, which can reduce maintenance costs.
Optimization Approach:Maximize energy capture by adjusting the blade angle or rotor speed in response to varying wind conditions. Use the available power from wind data to predict when the turbine should operate at full capacity or when it's better to curtail generation (e.g., during high winds to avoid overloading). Identify downtime due to technical reasons and address these bottlenecks through better maintenance or operational procedures.
Minimizing Downtime and Energy Losses
Relevant Variables:
WEC: ava. available P technical reasons
WEC: ava. available P force majeure reasons
WEC: ava. available P force external reasons
WEC: Production minutes
WEC: Operating Hours
Rationale: Downtime Unplanned downtime not only leads to lost production but also increases the costs of emergency repairs, which are typically more expensive than scheduled maintenance. Force majeure events (like extreme weather) can’t be controlled, but external factors such as grid curtailments can sometimes be mitigated with better planning or by coordinating with the grid operator.
Optimization Approach:Use historical data on production minutes and downtime to predict and schedule maintenance during periods of low wind or other downtime to reduce lost production. Analyze the causes of downtime due to technical or external reasons and identify trends or recurrent issues that can be mitigated through better operational planning. Implement condition monitoring systems to track performance and prevent unexpected failures, reducing the need for expensive, reactive maintenance.
Maintenance Scheduling and Predictive Maintenance
Relevant Variables:
Error
Time
WEC: Operating Hours
WEC: Production minutes
Rationale: Efficiently scheduling maintenance activities to minimize downtime is critical for maximizing energy production. Predictive maintenance, driven by data on operating hours, production minutes, and temperature conditions, can prevent unexpected failures and reduce costs associated with unplanned downtime.
Cost Implications:Scheduled maintenance is significantly less expensive than emergency repairs. Planning maintenance during low wind periods reduces revenue loss from downtime. Proactive component replacement can prevent costly failures and extend the overall operational lifespan of turbines.
Optimization Approach:Use operating hours and error data to schedule maintenance during periods of low wind or low energy demand. Implement predictive algorithms that trigger maintenance before critical failures occur, reducing both downtime and repair costs. Analyze error patterns and other historical data to predict when specific components will need servicing or replacement, avoiding emergency repairs that can disrupt energy production.
